"""Phase 3: exploit-engine containment -- mandatory scope gate + payload
sandbox for :class:`~.exploit_engine.ExploitEngine`.

``ExploitEngine`` already never sends a destructive payload (see its module
docstring): every candidate is capped at ``max_intrusion="low"`` with
destructive vectors excluded outright, independent of ``--allow-destructive``.
This module adds an orthogonal safeguard on top of that: it never lets the
engine run against a target *at all* unless the target is either a
recognisably-owned lab environment or the operator has explicitly taken
responsibility for the run, and it can rewrite the one payload category that
actually spawns a host command (``command_injection``) into an inert
verification echo before it is ever sent.

Two independent knobs:

* :class:`SafetyGate` -- an allow/abort decision for a *target host*. A host
  is in lab scope when it is a private/loopback/link-local address (RFC 1918
  and friends, via :mod:`ipaddress`), ``localhost``/``*.localhost``, or
  matches an operator-supplied ``--containment-allowed-domain``. Anything
  else requires ``--acknowledge-offensive-payloads`` -- an explicit,
  affirmative exemption -- or the gate refuses the target outright
  (:meth:`SafetyGate.enforce` raises :class:`ScopeDeviationError`;
  :meth:`SafetyGate.evaluate` returns a non-raising
  :class:`ContainmentDecision` for callers, such as the running engine, that
  need to skip-and-continue rather than abort).

* :class:`ContainmentProfile` -- ``STRICT`` permits the engine's existing
  real (but already non-destructive, low-intrusion) probes to run as
  :data:`ContainmentVector.CONTROLLED_EXECUTION`. ``SIMULATION`` (the
  default) goes one step further for the one payload category that spawns an
  actual host command: :class:`PayloadSandbox` rewrites the command to an
  inert ``echo`` of a single-use token generated by this process, so
  *nothing but that token* ever reaches the target's command interpreter,
  tagged :data:`ContainmentVector.CONTAINED_SIMULATION`.

Every decision this module makes is meant to be recorded verbatim into the
scan's forensic telemetry (:class:`~...core.telemetry_engine.
ContainmentMetrics`) and into each :class:`~.exploit_engine.ExploitAttempt`'s
``containment_vector``/``containment_profile`` fields, so a report reader can
see, per attempt, exactly what was and wasn't actually executed.
"""

from __future__ import annotations

import ipaddress
import re
import secrets
from dataclasses import dataclass
from enum import Enum
from urllib.parse import urlparse

__all__ = [
    "ContainmentProfile",
    "ContainmentVector",
    "ScopeDeviationError",
    "ContainmentDecision",
    "SafetyGate",
    "PayloadSandbox",
    "DEFAULT_MAX_EXPLOIT_DEPTH",
    "DEFAULT_CONTAINMENT_PROFILE",
]

# Bound on how many chained post-exploitation verification echoes the exploit
# engine performs after a single CONFIRMED_EXPLOITABLE command_injection
# finding, in ContainmentProfile.SIMULATION. 1 == the base Proof-of-Impact
# probe only, no chaining -- see ExploitEngine._chain_post_exploitation.
DEFAULT_MAX_EXPLOIT_DEPTH = 1

DEFAULT_CONTAINMENT_PROFILE = "simulation"

_LOCALHOST_SUFFIX = ".localhost"


class ContainmentProfile(str, Enum):
    """``--containment-profile`` choice."""

    #: Real (already non-destructive, low-intrusion) probes run as-is.
    STRICT = "strict"
    #: Command-injection payloads are rewritten to an inert token echo.
    SIMULATION = "simulation"


class ContainmentVector(str, Enum):
    """Audit-trail tag for what actually reached the target."""

    #: The payload sent was rewritten into a harmless verification echo --
    #: nothing the target's own command interpreter does is attacker-chosen.
    CONTAINED_SIMULATION = "CONTAINED_SIMULATION"
    #: The original, already-vetted low-intrusion evidence probe was sent.
    CONTROLLED_EXECUTION = "CONTROLLED_EXECUTION"


class ScopeDeviationError(RuntimeError):
    """Raised by :meth:`SafetyGate.enforce` when a target is out of lab scope
    and no exemption was granted.

    Meant to be caught at the CLI boundary (``cli.py``'s ``_validate_args``)
    to produce a deterministic, non-zero-exit error before any request is
    ever sent -- not caught deep inside the async scan pipeline, which
    should instead call :meth:`SafetyGate.evaluate` and skip the offending
    target (see ``ExploitEngine.run``).
    """


@dataclass(frozen=True)
class ContainmentDecision:
    """Non-raising verdict for one target host."""

    host: str
    allowed: bool
    in_lab_scope: bool
    reason: str


def _is_rfc1918_or_local(host: str) -> bool:
    """True for a private/loopback/link-local IP literal, ``localhost`` or a
    ``*.localhost`` name. Deliberately does no DNS resolution -- this must
    stay a cheap, synchronous, deterministic check callable from CLI argument
    validation before any event loop exists."""
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        host_l = host.lower()
        return host_l == "localhost" or host_l.endswith(_LOCALHOST_SUFFIX)
    return bool(ip.is_private or ip.is_loopback or ip.is_link_local)


class SafetyGate:
    """Mandatory scope gate for the exploit engine.

    Not a general SSRF guard (that already exists, and protects the *scanner*
    from being redirected somewhere unintended -- see
    ``core.scanner_core_async.PinnedResolver``). This is the opposite
    direction: it protects a *third party* from being on the receiving end of
    an offensive/RCE-flavoured payload the operator never meant to fire
    outside their own lab.
    """

    def __init__(
        self,
        *,
        allowed_domains: tuple[str, ...] = (),
        acknowledge_offensive_payloads: bool = False,
    ) -> None:
        self._allowed_domains = tuple(
            d.strip().lower().lstrip(".") for d in allowed_domains if d and d.strip()
        )
        self._acknowledge = bool(acknowledge_offensive_payloads)

    @property
    def acknowledge_offensive_payloads(self) -> bool:
        return self._acknowledge

    def _host_allowlisted(self, host: str) -> bool:
        host_l = host.lower()
        return any(host_l == d or host_l.endswith("." + d) for d in self._allowed_domains)

    def evaluate(self, url: str) -> ContainmentDecision:
        """Non-raising verdict for ``url``'s host."""
        host = urlparse(url).hostname or ""
        if not host:
            return ContainmentDecision(host, False, False, "URL has no host component.")

        in_scope = _is_rfc1918_or_local(host) or self._host_allowlisted(host)
        if in_scope:
            return ContainmentDecision(
                host, True, True,
                "Host resolves to a private/loopback/link-local range, "
                "localhost, or an explicitly allowed lab domain.",
            )
        if self._acknowledge:
            return ContainmentDecision(
                host, True, False,
                "Host is outside recognised lab ranges, but "
                "--acknowledge-offensive-payloads was passed: the operator "
                "explicitly accepted responsibility for this target.",
            )
        return ContainmentDecision(
            host, False, False,
            "Host is outside RFC 1918/loopback/link-local ranges, localhost "
            "and every --containment-allowed-domain, and "
            "--acknowledge-offensive-payloads was not passed.",
        )

    def enforce(self, url: str) -> ContainmentDecision:
        """Same as :meth:`evaluate`, but raises :class:`ScopeDeviationError`
        instead of returning a refusing decision. Use at a hard boundary
        (CLI startup) where an out-of-scope target must abort the run
        immediately rather than be silently skipped."""
        decision = self.evaluate(url)
        if not decision.allowed:
            raise ScopeDeviationError(
                f"Safety Gate refused target host {decision.host!r}: {decision.reason} "
                "Pass --acknowledge-offensive-payloads to run the exploit engine "
                "against this target anyway, or point it at a lab host "
                "(RFC 1918 / loopback / localhost / --containment-allowed-domain)."
            )
        return decision


# ---------------------------------------------------------------------------
# Payload sandbox
# ---------------------------------------------------------------------------

# The only payload category the exploit engine ever adapts to that spawns a
# real host command (see exploit_engine._RCE_CATEGORY_BY_LANGUAGE) -- ssti
# payloads are template-engine arithmetic and deserialization payloads probe
# for a parser's own error signature, neither of which runs an attacker
# command on the host at all. This is deliberately narrow: sandboxing only
# what actually executes something.
SANDBOXED_CATEGORY = "command_injection"

# Recognised benign command tokens the curated command_injection corpus uses
# as its evidence probe (``id``, a version banner, a fixed-path read, ...).
# Matched case-sensitively -- the corpus's own vectors are lower-case shell
# commands -- and replaced wholesale with an inert echo of this process's
# one-time verification token.
_COMMAND_TOKEN_RE = re.compile(
    r"\b(?:id|whoami|uname\s+-a|hostname|cat\s+/etc/passwd|dir|type\s+\S+|ver|"
    r"ping\s+-[nc]\s+\d+\s+\S+)\b"
)


class PayloadSandbox:
    """Rewrites a ``command_injection`` payload vector into an inert
    verification echo.

    Every token this generates is unique per call (``secrets.token_hex``), so
    a reproduced token in the response can only mean this exact sandboxed
    probe executed -- never a coincidental match against unrelated page
    content, the same non-destructive-evidence guarantee
    :class:`~.exploit_engine.ExploitEngine` already relies on for its
    real probes.
    """

    @staticmethod
    def make_token() -> str:
        return f"CONTAIN_{secrets.token_hex(8)}"

    def sandbox_command(self, vector: str) -> tuple[str, str]:
        """Returns ``(sandboxed_vector, verification_token)``.

        Replaces the corpus's own benign command token (``id``, ``whoami``,
        ...) with ``echo <token>``, so the exact same injection
        separator/context the payload already carries (``; id``, ``| id``,
        ``$(id)``, ...) now runs a harmless echo instead. When the vector's
        command shape isn't one of the recognised tokens, the token is
        appended after the vector's own separator as a best-effort fallback
        -- still non-destructive, since it only ever adds an ``echo``, never
        removes or alters what was already there.
        """
        token = self.make_token()
        sandboxed, replaced = _COMMAND_TOKEN_RE.subn(f"echo {token}", vector, count=1)
        if not replaced:
            sandboxed = f"{vector} echo {token}"
        return sandboxed, token
