CMS_fingerprints = {
    # CMS populares
    'wordpress': 'WordPress',
    'joomla': 'Joomla',
    'drupal': 'Drupal',
    'magento': 'Magento',
    'prestashop': 'PrestaShop',
    'opencart': 'OpenCart',
    'shopify': 'Shopify',
    'wix': 'Wix',
    'squarespace': 'Squarespace',
    'typo3': 'TYPO3',
    'ghost': 'Ghost',
    'blogger': 'Blogger',
    'weebly': 'Weebly',
    'phpbb': 'phpBB',
    'vbulletin': 'vBulletin',
    'moodle': 'Moodle',
    'dotnetnuke': 'DotNetNuke',
    'sitefinity': 'Sitefinity',
    'umbraco': 'Umbraco',
    'plone': 'Plone',
    'concrete5': 'Concrete5',
    'craftcms': 'Craft CMS',
    'expressionengine': 'ExpressionEngine',
    'silverstripe': 'SilverStripe',
    'contao': 'Contao',
    'serendipity': 'Serendipity',
    'textpattern': 'Textpattern',
    'b2evolution': 'b2evolution',
    'zendesk': 'Zendesk',
    'oscommerce': 'osCommerce',
    'bigcommerce': 'BigCommerce',
    'xenforo': 'XenForo',
    'discuz': 'Discuz!',
    'dede': 'Dedecms',
    'ecshop': 'ECShop',
    'zencart': 'Zen Cart',
    'phpnuke': 'PHP-Nuke',
    'mediawiki': 'MediaWiki',
    'dokuwiki': 'DokuWiki',
    'tikiwiki': 'Tiki Wiki CMS Groupware',
    'liferay': 'Liferay',
    'kentico': 'Kentico',
    'episerver': 'Episerver',
    'sitecore': 'Sitecore',
    'blogengine': 'BlogEngine.NET',
    'nucleus': 'Nucleus CMS',
    'movabletype': 'Movable Type',
    'subrion': 'Subrion',
    'jshop': 'JShop',
    'nopcommerce': 'nopCommerce',
    'cs-cart': 'CS-Cart',
    'prestashop': 'PrestaShop',
    'shopware': 'Shopware',
    'spip': 'SPIP',
    'e107': 'e107',
    'simplemachines': 'Simple Machines Forum',
    'mybb': 'MyBB',
    'punbb': 'PunBB',
    'fluxbb': 'FluxBB',
    'vanilla': 'Vanilla Forums',
    # Frameworks y librerías JS populares
    'jquery': 'jQuery',
    'angular': 'Angular',
    'react': 'React',
    'vue': 'Vue.js',
    'backbone': 'Backbone.js',
    'ember': 'Ember.js',
    'mootools': 'MooTools',
    'prototype': 'Prototype',
    'dojo': 'Dojo',
    'extjs': 'ExtJS',
    'underscore': 'Underscore.js',
    'lodash': 'Lodash',
    'moment': 'Moment.js',
    'bootstrap': 'Bootstrap',
    'foundation': 'Foundation',
    'materialize': 'Materialize',
    'bulma': 'Bulma',
    'tailwind': 'Tailwind CSS',
    'd3': 'D3.js',
    'chart': 'Chart.js',
    'three': 'Three.js',
    'gsap': 'GSAP',
    'anime': 'Anime.js',
    'axios': 'Axios',
    'fetch': 'Fetch API',
    'socketio': 'Socket.IO'
}