JSframeworks = {
    'jquery': 'jQuery',
    'angular': 'Angular',
    'react': 'React',
    'vue': 'Vue.js',
    'backbone': 'Backbone.js',
    'ember': 'Ember.js',
    'mootools': 'MooTools',
    'prototype': 'Prototype',
    'dojo': 'Dojo',
    'extjs': 'ExtJS',
    'underscore': 'Underscore.js',
    'lodash': 'Lodash',
    'moment': 'Moment.js',
    'bootstrap': 'Bootstrap',
    'foundation': 'Foundation',
    'materialize': 'Materialize',
    'bulma': 'Bulma',
    'tailwind': 'Tailwind CSS',
    'd3': 'D3.js',
    'chart': 'Chart.js',
    'three': 'Three.js',
    'gsap': 'GSAP',
    'anime': 'Anime.js',
    'axios': 'Axios',
    'fetch': 'Fetch API',
    'socketio': 'Socket.IO',
    # Mejoras y frameworks/librerías adicionales
    'next': 'Next.js',
    'nuxt': 'Nuxt.js',
    'svelte': 'Svelte',
    'sapper': 'Sapper',
    'alpine': 'Alpine.js',
    'stimulus': 'Stimulus',
    'meteor': 'Meteor',
    'polymer': 'Polymer',
    'knockout': 'Knockout.js',
    'mithril': 'Mithril.js',
    'riot': 'Riot.js',
    'marko': 'Marko',
    'preact': 'Preact',
    'inferno': 'Inferno',
    'redux': 'Redux',
    'mobx': 'MobX',
    'rxjs': 'RxJS',
    'zepto': 'Zepto.js',
    'ember-data': 'Ember Data',
    'apollo': 'Apollo Client',
    'relay': 'Relay',
    'enzyme': 'Enzyme',
    'jest': 'Jest',
    'cypress': 'Cypress',
    'mocha': 'Mocha',
    'chai': 'Chai',
    'sinon': 'Sinon.js',
    'qunit': 'QUnit',
    'ava': 'AVA',
    'tape': 'Tape',
    'babel': 'Babel',
    'webpack': 'Webpack',
    'parcel': 'Parcel',
    'rollup': 'Rollup',
    'grunt': 'Grunt',
    'gulp': 'Gulp',
    'esbuild': 'esbuild',
    'vite': 'Vite',
    'popper': 'Popper.js',
    'swiper': 'Swiper.js',
    'fullcalendar': 'FullCalendar',
    'handsontable': 'Handsontable',
    'tabulator': 'Tabulator',
    'ag-grid': 'AG Grid',
    'highcharts': 'Highcharts',
    'echarts': 'ECharts',
    'leaflet': 'Leaflet',
    'openlayers': 'OpenLayers',
    'mapbox': 'Mapbox GL JS',
    'videojs': 'Video.js',
    'plyr': 'Plyr',
    'pdfjs': 'PDF.js',
    'zxing': 'ZXing',
    'quasar': 'Quasar Framework',
    'vuetify': 'Vuetify',
    'element': 'Element UI',
    'primevue': 'PrimeVue',
    'primefaces': 'PrimeFaces',
    'antdv': 'Ant Design Vue',
    'antdesign': 'Ant Design React',
    'semantic': 'Semantic UI',
    'materialui': 'Material-UI',
    'blueprint': 'Blueprint.js'
}

